# docker-compose.yml
version: "3.7"
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}

    ports:
      - "${POSTGRES_PORT:-54321}:5432"
