after "development:001-gas_types", "development:001-sensor_types", "development:020-service_objects" do
Sensor.destroy_all

(0..10).each do |i|
  Sensor.create!({
    central_device: $central_device1,
    gas_type: $gas_type1,
    sensor_type: $sensor_type1,
    min_value: 0,
    max_value: 100,
    application_date: DateTime.parse("01.06.2019"),
    livetime: 2.years.since(DateTime.parse("01.06.2019")),
    alarm_point_1: 20,
    alarm_point_2: 40,
    alarm_point_3: nil,
    alarm_point_4: nil,
    si_unit: $si_unit1,
    location: "Messtechnik Boden",
    number: 1,
    })

    Sensor.create!({
      central_device: $central_device1,
      gas_type: $gas_type2,
      sensor_type: $sensor_type2,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 2.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit1,
      location: "Messtechnik Boden",
      number: 1,
    })
end

$sensor2 = Sensor.create!({
  central_device: $central_device1,
  gas_type: $gas_type2,
  sensor_type: $sensor_type2,
  min_value: 0,
  max_value: 100,
  application_date: DateTime.parse("01.06.2019"),
  livetime: 2.years.since(DateTime.parse("01.06.2019")),
  alarm_point_1: 20,
  alarm_point_2: 40,
  alarm_point_3: nil,
  alarm_point_4: nil,
  si_unit: $si_unit1,
  location: "Messtechnik Boden",
  number: 1,
})

$sensor3 = Sensor.create!({
  central_device: $central_device1,
  gas_type: $gas_type3,
  sensor_type: $sensor_type3,
  min_value: 0,
  max_value: 100,
  application_date: DateTime.parse("01.06.2019"),
  livetime: 2.years.since(DateTime.parse("01.06.2019")),
  alarm_point_1: 20,
  alarm_point_2: 40,
  alarm_point_3: nil,
  alarm_point_4: nil,
  si_unit: $si_unit1,
  location: "Messtechnik Boden",
  number: 1,
})

# Sensor.create!(
#   [
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 2.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnik Boden",
#       number: 1,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 20,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 3.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 5,
#       alarm_point_2: 8,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnik rechts",
#       number: 2,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 25,
#       application_date: DateTime.parse("01.07.2019"),
#       livetime: 1.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 19,
#       alarm_point_2: 17,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnik rechts",
#       number: 3,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 300,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.06.2018")),
#       alarm_point_1: 60,
#       alarm_point_2: 120,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnik rechts",
#       number: 4,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.06.2018")),
#       alarm_point_1: 10,
#       alarm_point_2: 25,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnik Decke",
#       number: 5,
#     },
#     # END Block 1
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 300,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.07.2018")),
#       alarm_point_1: 60,
#       alarm_point_2: 120,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnik links",
#       number: 7,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 20,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 3.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 3,
#       alarm_point_2: 6,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnik links",
#       number: 8,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 3.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Leistungs- Abgasprüfstand unter K2",
#       number: 9,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2017"),
#       livetime: 3.years.since(DateTime.parse("01.06.2017")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Leistungs- Abgasprüfstand oben Rolle1",
#       number: 10,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 300,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.07.2018")),
#       alarm_point_1: 30,
#       alarm_point_2: 60,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Leistungs- Abgasprüfstand Rolle1",
#       number: 11,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 300,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.07.2018")),
#       alarm_point_1: 30,
#       alarm_point_2: 60,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "NVH Rollenprüfstand 2 oben",
#       number: 12,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2017"),
#       livetime: 3.years.since(DateTime.parse("01.06.2017")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "NVH Rollenprüfstand 2 oben",
#       number: 13,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2017"),
#       livetime: 3.years.since(DateTime.parse("01.06.2017")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "NVH Rollenprüfstand 2 unten",
#       number: 14,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2017"),
#       livetime: 3.years.since(DateTime.parse("01.06.2017")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Triebstrang ATS 1 unten",
#       number: 15,
#     },
#     # END block 2
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 300,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.07.2018")),
#       alarm_point_1: 30,
#       alarm_point_2: 300,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Triebstrang ATS 1 oben",
#       number: 17,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 2.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Triebstrang ATS 1 oben",
#       number: 18,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.06.2018")),
#       alarm_point_1: 10,
#       alarm_point_2: 25,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Kanal Klimazentrale 2. OG",
#       number: 19,
#     },
#     # END block 3
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.06.2018")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "ATS 2 - oben",
#       number: 25,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 300,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.07.2018")),
#       alarm_point_1: 30,
#       alarm_point_2: 300,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "ATS 2 - oben",
#       number: 26,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.06.2018")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "ATS 2 - unten",
#       number: 27,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 300,
#       application_date: DateTime.parse("01.07.2018"),
#       livetime: 2.years.since(DateTime.parse("01.07.2018")),
#       alarm_point_1: 30,
#       alarm_point_2: 60,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Abgasanalyselabor",
#       number: 28,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 20,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 3.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 3,
#       alarm_point_2: 6,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Abgasanalyselabor",
#       number: 29,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2017"),
#       livetime: 3.years.since(DateTime.parse("01.07.2017")),
#       alarm_point_1: 10,
#       alarm_point_2: 25,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Abgasanalyselabor",
#       number: 30,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2017"),
#       livetime: 3.years.since(DateTime.parse("01.07.2017")),
#       alarm_point_1: 20,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Abgasanalyselabor",
#       number: 31
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2019"),
#       livetime: 3.years.since(DateTime.parse("01.07.2019")),
#       alarm_point_1: 10,
#       alarm_point_2: 25,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Batterieladung",
#       number: 32,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.07.2019"),
#       livetime: 3.years.since(DateTime.parse("01.07.2019")),
#       alarm_point_1: 10,
#       alarm_point_2: 25,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Batterieladung",
#       number: 33,
#     },
#     # END block 4
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: nil,
#       max_value: nil,
#       application_date: nil,
#       livetime: nil,
#       alarm_point_1: nil,
#       alarm_point_2: 100,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "NVH Rolle 2 unten",
#       number: 35,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: nil,
#       max_value: nil,
#       application_date: nil,
#       livetime: nil,
#       alarm_point_1: nil,
#       alarm_point_2: 100,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Kälterolle",
#       number: 36,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: nil,
#       max_value: nil,
#       application_date: nil,
#       livetime: nil,
#       alarm_point_1: nil,
#       alarm_point_2: 100,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "ATS 1 unten",
#       number: 37,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: nil,
#       max_value: nil,
#       application_date: nil,
#       livetime: nil,
#       alarm_point_1: nil,
#       alarm_point_2: 100,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "ATS 2 unten",
#       number: 38,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 3.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 25,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnikraum",
#       number: 39,
#     },
#     {
#       central_device: central_device1,
#       gas_type: gas_type1,
#       sensor_type: sensor_type1,
#       min_value: 0,
#       max_value: 100,
#       application_date: DateTime.parse("01.06.2019"),
#       livetime: 3.years.since(DateTime.parse("01.06.2019")),
#       alarm_point_1: 25,
#       alarm_point_2: 40,
#       alarm_point_3: nil,
#       alarm_point_4: nil,
#       si_unit: si_unit1,
#       location: "Messtechnikraum",
#       number: 40,
#     },
#   ]
# )
end
