$sensors = Sensor.create(
  [
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 2.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Messtechnik Boden",
      number: 1,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_no2,
      sensor_type: $sensor_type_no2,
      min_value: 0,
      max_value: 20,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 3.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 5,
      alarm_point_2: 8,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Messtechnik rechts",
      number: 2,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_o2,
      sensor_type: $sensor_type_o2,
      min_value: 0,
      max_value: 25,
      application_date: DateTime.parse("01.07.2019"),
      livetime: 1.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 19,
      alarm_point_2: 17,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_vol,
      location: "Messtechnik rechts",
      number: 3,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_co,
      sensor_type: $sensor_type_co,
      min_value: 0,
      max_value: 300,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.06.2018")),
      alarm_point_1: 60,
      alarm_point_2: 120,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Messtechnik rechts",
      number: 4,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_h2,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.06.2018")),
      alarm_point_1: 10,
      alarm_point_2: 25,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Messtechnik Decke",
      number: 5,
    },
    # END Block 1
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_co,
      sensor_type: $sensor_type_co,
      min_value: 0,
      max_value: 300,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.07.2018")),
      alarm_point_1: 60,
      alarm_point_2: 120,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Messtechnik links",
      number: 7,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_no2,
      sensor_type: $sensor_type_no2,
      min_value: 0,
      max_value: 20,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 3.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 3,
      alarm_point_2: 6,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Messtechnik links",
      number: 8,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 3.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Leistungs- Abgasprüfstand unter K2",
      number: 9,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2017"),
      livetime: 3.years.since(DateTime.parse("01.06.2017")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Leistungs- Abgasprüfstand oben Rolle1",
      number: 10,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_co,
      sensor_type: $sensor_type_co,
      min_value: 0,
      max_value: 300,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.07.2018")),
      alarm_point_1: 30,
      alarm_point_2: 60,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Leistungs- Abgasprüfstand Rolle1",
      number: 11,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_co,
      sensor_type: $sensor_type_co,
      min_value: 0,
      max_value: 300,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.07.2018")),
      alarm_point_1: 30,
      alarm_point_2: 60,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "NVH Rollenprüfstand 2 oben",
      number: 12,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2017"),
      livetime: 3.years.since(DateTime.parse("01.06.2017")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "NVH Rollenprüfstand 2 oben",
      number: 13,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2017"),
      livetime: 3.years.since(DateTime.parse("01.06.2017")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "NVH Rollenprüfstand 2 unten",
      number: 14,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2017"),
      livetime: 3.years.since(DateTime.parse("01.06.2017")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Triebstrang ATS 1 unten",
      number: 15,
    },
    # END block 2
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_co,
      sensor_type: $sensor_type_co,
      min_value: 0,
      max_value: 300,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.07.2018")),
      alarm_point_1: 30,
      alarm_point_2: 300,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Triebstrang ATS 1 oben",
      number: 17,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 2.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Triebstrang ATS 1 oben",
      number: 18,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_h2,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.06.2018")),
      alarm_point_1: 10,
      alarm_point_2: 25,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Kanal Klimazentrale 2. OG",
      number: 19,
    },
    # END block 3
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_h2,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.06.2018")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "ATS 2 - oben",
      number: 25,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_co,
      sensor_type: $sensor_type_co,
      min_value: 0,
      max_value: 300,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.07.2018")),
      alarm_point_1: 30,
      alarm_point_2: 300,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "ATS 2 - oben",
      number: 26,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_h2,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.06.2018")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "ATS 2 - unten",
      number: 27,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_co,
      sensor_type: $sensor_type_co,
      min_value: 0,
      max_value: 300,
      application_date: DateTime.parse("01.07.2018"),
      livetime: 2.years.since(DateTime.parse("01.07.2018")),
      alarm_point_1: 30,
      alarm_point_2: 60,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Abgasanalyselabor",
      number: 28,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_no2,
      sensor_type: $sensor_type_no2,
      min_value: 0,
      max_value: 20,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 3.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 3,
      alarm_point_2: 6,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Abgasanalyselabor",
      number: 29,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_h2,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2017"),
      livetime: 3.years.since(DateTime.parse("01.07.2017")),
      alarm_point_1: 10,
      alarm_point_2: 25,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Abgasanalyselabor",
      number: 30,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_hc,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2017"),
      livetime: 3.years.since(DateTime.parse("01.07.2017")),
      alarm_point_1: 20,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Abgasanalyselabor",
      number: 31
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_h2,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2019"),
      livetime: 3.years.since(DateTime.parse("01.07.2019")),
      alarm_point_1: 10,
      alarm_point_2: 25,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Batterieladung",
      number: 32,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_h2,
      sensor_type: $sensor_type_nap55,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.07.2019"),
      livetime: 3.years.since(DateTime.parse("01.07.2019")),
      alarm_point_1: 10,
      alarm_point_2: 25,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ueg,
      location: "Batterieladung",
      number: 33,
    },
    # END block 4
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_empty,
      sensor_type: $sensor_type_leckage,
      min_value: nil,
      max_value: nil,
      application_date: nil,
      livetime: nil,
      alarm_point_1: nil,
      alarm_point_2: 100,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_empty,
      location: "NVH Rolle 2 unten",
      number: 35,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_empty,
      sensor_type: $sensor_type_leckage,
      min_value: nil,
      max_value: nil,
      application_date: nil,
      livetime: nil,
      alarm_point_1: nil,
      alarm_point_2: 100,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_empty,
      location: "Kälterolle",
      number: 36,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_empty,
      sensor_type: $sensor_type_leckage,
      min_value: nil,
      max_value: nil,
      application_date: nil,
      livetime: nil,
      alarm_point_1: nil,
      alarm_point_2: 100,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_empty,
      location: "ATS 1 unten",
      number: 37,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_empty,
      sensor_type: $sensor_type_leckage,
      min_value: nil,
      max_value: nil,
      application_date: nil,
      livetime: nil,
      alarm_point_1: nil,
      alarm_point_2: 100,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_empty,
      location: "ATS 2 unten",
      number: 38,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_no,
      sensor_type: $sensor_type_no,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 3.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 25,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Messtechnikraum",
      number: 39,
    },
    {
      central_device: $service_object_avl,
      gas_type: $gas_type_no,
      sensor_type: $sensor_type_no,
      min_value: 0,
      max_value: 100,
      application_date: DateTime.parse("01.06.2019"),
      livetime: 3.years.since(DateTime.parse("01.06.2019")),
      alarm_point_1: 25,
      alarm_point_2: 40,
      alarm_point_3: nil,
      alarm_point_4: nil,
      si_unit: $si_unit_ppm,
      location: "Messtechnikraum",
      number: 40,
    },
  ]
)
